"""
Multi-language Support for Defactra AI Reports
Languages: English, Malayalam, Hindi
"""

TRANSLATIONS = {
    'english': {
        # Headers
        'report_title': 'Property Inspection Report',
        'generated_by': 'Generated by Defactra AI',
        'inspection_date': 'Inspection Date',
        'property_details': 'Property Details',
        'executive_summary': 'Executive Summary',
        'defect_analysis': 'Defect Analysis',
        'risk_assessment': 'Risk Assessment',
        'recommendations': 'Recommendations',

        # Property Info
        'property_id': 'Property ID',
        'address': 'Address',
        'city': 'City',
        'property_type': 'Type',
        'bedrooms': 'Bedrooms',
        'area': 'Area (sq ft)',
        'year_built': 'Year Built',
        'room_name': 'Room',

        # Summary
        'overall_condition': 'Overall Condition Score',
        'total_defects': 'Total Defects Found',
        'critical_issues': 'Critical Issues',
        'high_priority': 'High Priority',
        'medium_priority': 'Medium Priority',
        'low_priority': 'Low Priority',
        'usability_rating': 'Usability Rating',

        # Defect Details
        'defect_details': 'Detailed Defect Information',
        'severity': 'Severity',
        'location': 'Location',
        'confidence': 'Detection Confidence',
        'description': 'Description',
        'impact': 'Impact',
        'repair_priority': 'Repair Priority',

        # Severity Levels
        'critical': 'CRITICAL',
        'high': 'HIGH',
        'medium': 'MEDIUM',
        'low': 'LOW',

        # Repair Priority
        'immediate': 'Immediate Action Required',
        'urgent': 'Urgent - Within 7 Days',
        'routine': 'Routine - Within 30 Days',
        'cosmetic': 'Cosmetic - Schedule as Convenient',

        # Recommendations
        'rec_critical': 'Immediate professional inspection and repair required for safety.',
        'rec_high': 'Schedule professional repair within the next week to prevent further damage.',
        'rec_medium': 'Plan repairs within 1-2 months to maintain property value.',
        'rec_low': 'Minor maintenance can be scheduled at convenience.',
        'rec_general': 'Regular maintenance and periodic inspections are recommended.',

        # Risk Categories
        'high_risk': 'High Risk',
        'medium_risk': 'Medium Risk',
        'low_risk': 'Low Risk',

        # Footer
        'disclaimer': 'This report is based on AI analysis and should be verified by a professional inspector.',
        'page': 'Page',
        'of': 'of',
    },

    'malayalam': {
        # Headers
        'report_title': 'വസ്തു പരിശോധന റിപ്പോർട്ട്',
        'generated_by': 'ഡിഫാക്ട്ര AI നിർമ്മിച്ചത്',
        'inspection_date': 'പരിശോധന തീയതി',
        'property_details': 'വസ്തുവിന്റെ വിശദാംശങ്ങൾ',
        'executive_summary': 'എക്സിക്യൂട്ടീവ് സംഗ്രഹം',
        'defect_analysis': 'കേടുപാടുകളുടെ വിശകലനം',
        'risk_assessment': 'അപകട വിലയിരുത്തൽ',
        'recommendations': 'ശുപാർശകൾ',

        # Property Info
        'property_id': 'വസ്തു ഐഡി',
        'address': 'വിലാസം',
        'city': 'നഗരം',
        'property_type': 'തരം',
        'bedrooms': 'കിടപ്പുമുറികൾ',
        'area': 'വിസ്തീർണ്ണം (ചതുരശ്ര അടി)',
        'year_built': 'നിർമ്മിച്ച വർഷം',
        'room_name': 'മുറി',

        # Summary
        'overall_condition': 'മൊത്തം അവസ്ഥ സ്കോർ',
        'total_defects': 'ആകെ കേടുപാടുകൾ',
        'critical_issues': 'ഗുരുതര പ്രശ്നങ്ങൾ',
        'high_priority': 'ഉയർന്ന മുൻഗണന',
        'medium_priority': 'ഇടത്തരം മുൻഗണന',
        'low_priority': 'കുറഞ്ഞ മുൻഗണന',
        'usability_rating': 'ഉപയോഗക്ഷമത റേറ്റിംഗ്',

        # Defect Details
        'defect_details': 'വിശദമായ കേടുപാട് വിവരങ്ങൾ',
        'severity': 'തീവ്രത',
        'location': 'സ്ഥലം',
        'confidence': 'കണ്ടെത്തൽ ആത്മവിശ്വാസം',
        'description': 'വിവരണം',
        'impact': 'ആഘാതം',
        'repair_priority': 'അറ്റകുറ്റപ്പണി മുൻഗണന',

        # Severity Levels
        'critical': 'അത്യാവശ്യം',
        'high': 'ഉയർന്നത്',
        'medium': 'ഇടത്തരം',
        'low': 'കുറഞ്ഞത്',

        # Repair Priority
        'immediate': 'ഉടനടി നടപടി ആവശ്യമാണ്',
        'urgent': 'അടിയന്തിരം - 7 ദിവസത്തിനുള്ളിൽ',
        'routine': 'പതിവ് - 30 ദിവസത്തിനുള്ളിൽ',
        'cosmetic': 'സൗന്ദര്യാത്മകം - സൗകര്യം അനുസരിച്ച്',

        # Recommendations
        'rec_critical': 'സുരക്ഷയ്ക്കായി ഉടനടി പ്രൊഫഷണൽ പരിശോധനയും അറ്റകുറ്റപ്പണിയും ആവശ്യമാണ്.',
        'rec_high': 'കൂടുതൽ നാശനഷ്ടം തടയാൻ അടുത്ത ആഴ്ചയിൽ പ്രൊഫഷണൽ അറ്റകുറ്റപ്പണി ഷെഡ്യൂൾ ചെയ്യുക.',
        'rec_medium': 'വസ്തുവിന്റെ മൂല്യം നിലനിർത്താൻ 1-2 മാസത്തിനുള്ളിൽ അറ്റകുറ്റപ്പണികൾ ആസൂത്രണം ചെയ്യുക.',
        'rec_low': 'ചെറിയ അറ്റകുറ്റപ്പണികൾ സൗകര്യം അനുസരിച്ച് ഷെഡ്യൂൾ ചെയ്യാം.',
        'rec_general': 'പതിവ് അറ്റകുറ്റപ്പണികളും ആനുകാലിക പരിശോധനകളും ശുപാർശ ചെയ്യുന്നു.',

        # Risk Categories
        'high_risk': 'ഉയർന്ന അപകടസാധ്യത',
        'medium_risk': 'ഇടത്തരം അപകടസാധ്യത',
        'low_risk': 'കുറഞ്ഞ അപകടസാധ്യത',

        # Footer
        'disclaimer': 'ഈ റിപ്പോർട്ട് AI വിശകലനത്തെ അടിസ്ഥാനമാക്കിയുള്ളതാണ്, പ്രൊഫഷണൽ ഇൻസ്പെക്ടർ പരിശോധിക്കണം.',
        'page': 'പേജ്',
        'of': 'ൽ',
    },

    'hindi': {
        # Headers
        'report_title': 'संपत्ति निरीक्षण रिपोर्ट',
        'generated_by': 'डिफैक्ट्रा AI द्वारा निर्मित',
        'inspection_date': 'निरीक्षण तिथि',
        'property_details': 'संपत्ति विवरण',
        'executive_summary': 'कार्यकारी सारांश',
        'defect_analysis': 'दोष विश्लेषण',
        'risk_assessment': 'जोखिम मूल्यांकन',
        'recommendations': 'सिफारिशें',

        # Property Info
        'property_id': 'संपत्ति आईडी',
        'address': 'पता',
        'city': 'शहर',
        'property_type': 'प्रकार',
        'bedrooms': 'शयनकक्ष',
        'area': 'क्षेत्रफल (वर्ग फुट)',
        'year_built': 'निर्माण वर्ष',
        'room_name': 'कमरा',

        # Summary
        'overall_condition': 'समग्र स्थिति स्कोर',
        'total_defects': 'कुल दोष पाए गए',
        'critical_issues': 'गंभीर समस्याएं',
        'high_priority': 'उच्च प्राथमिकता',
        'medium_priority': 'मध्यम प्राथमिकता',
        'low_priority': 'कम प्राथमिकता',
        'usability_rating': 'उपयोगिता रेटिंग',

        # Defect Details
        'defect_details': 'विस्तृत दोष जानकारी',
        'severity': 'गंभीरता',
        'location': 'स्थान',
        'confidence': 'पता लगाने का विश्वास',
        'description': 'विवरण',
        'impact': 'प्रभाव',
        'repair_priority': 'मरम्मत प्राथमिकता',

        # Severity Levels
        'critical': 'गंभीर',
        'high': 'उच्च',
        'medium': 'मध्यम',
        'low': 'कम',

        # Repair Priority
        'immediate': 'तत्काल कार्रवाई आवश्यक',
        'urgent': 'जरूरी - 7 दिनों के भीतर',
        'routine': 'नियमित - 30 दिनों के भीतर',
        'cosmetic': 'कॉस्मेटिक - सुविधानुसार',

        # Recommendations
        'rec_critical': 'सुरक्षा के लिए तत्काल पेशेवर निरीक्षण और मरम्मत आवश्यक है।',
        'rec_high': 'आगे की क्षति को रोकने के लिए अगले सप्ताह में पेशेवर मरम्मत निर्धारित करें।',
        'rec_medium': 'संपत्ति मूल्य बनाए रखने के लिए 1-2 महीनों में मरम्मत की योजना बनाएं।',
        'rec_low': 'मामूली रखरखाव सुविधानुसार निर्धारित किया जा सकता है।',
        'rec_general': 'नियमित रखरखाव और आवधिक निरीक्षण की सिफारिश की जाती है।',

        # Risk Categories
        'high_risk': 'उच्च जोखिम',
        'medium_risk': 'मध्यम जोखिम',
        'low_risk': 'कम जोखिम',

        # Footer
        'disclaimer': 'यह रिपोर्ट AI विश्लेषण पर आधारित है और इसे पेशेवर निरीक्षक द्वारा सत्यापित किया जाना चाहिए।',
        'page': 'पृष्ठ',
        'of': 'का',
    }
}


def get_text(key, language='english'):
    """
    Get translated text for a given key

    Args:
        key: Translation key
        language: Language code (english, malayalam, hindi)

    Returns:
        Translated text
    """
    lang = language.lower()
    if lang not in TRANSLATIONS:
        lang = 'english'

    return TRANSLATIONS[lang].get(key, TRANSLATIONS['english'].get(key, key))


def get_severity_color(severity):
    """Get color for severity level"""
    colors = {
        'critical': '#FF0066',
        'high': '#FF6600',
        'medium': '#FFCC00',
        'low': '#00FF99'
    }
    return colors.get(severity.lower(), '#808080')


def get_priority_text(priority, language='english'):
    """Get repair priority text in specified language"""
    priority_map = {
        'immediate': 'immediate',
        'urgent': 'urgent',
        'routine': 'routine',
        'cosmetic': 'cosmetic'
    }
    key = priority_map.get(priority.lower(), 'routine')
    return get_text(key, language)